#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE02B14E5030A2708 (security@celeryproject.org)
#
Name     : case
Version  : 1.5.3
Release  : 18
URL      : https://files.pythonhosted.org/packages/31/5a/9f1040ffb91e62c7ed6068dab6da5e1cb9ca3642d9b63c2254c3393af483/case-1.5.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/31/5a/9f1040ffb91e62c7ed6068dab6da5e1cb9ca3642d9b63c2254c3393af483/case-1.5.3.tar.gz
Source99 : https://files.pythonhosted.org/packages/31/5a/9f1040ffb91e62c7ed6068dab6da5e1cb9ca3642d9b63c2254c3393af483/case-1.5.3.tar.gz.asc
Summary  : Python unittest Utilities
Group    : Development/Tools
License  : BSD-3-Clause
Requires: case-license = %{version}-%{release}
Requires: case-python = %{version}-%{release}
Requires: case-python3 = %{version}-%{release}
Requires: nose
Requires: python-mock
Requires: setuptools
Requires: six
Requires: unittest2
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : nose
BuildRequires : python-mock
BuildRequires : unittest2-python

%description
=====================================================================
Python unittest utilities
=====================================================================

%package license
Summary: license components for the case package.
Group: Default

%description license
license components for the case package.


%package python
Summary: python components for the case package.
Group: Default
Requires: case-python3 = %{version}-%{release}

%description python
python components for the case package.


%package python3
Summary: python3 components for the case package.
Group: Default
Requires: python3-core

%description python3
python3 components for the case package.


%prep
%setup -q -n case-1.5.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551038628
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/case
cp LICENSE %{buildroot}/usr/share/package-licenses/case/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/case/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
